services:
  app:
    build: .
    container_name: fintech-assets-explorer-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OCTANE_SERVER: swoole
      VITE_HOST: "0.0.0.0"
      VITE_PORT: 5173
      VITE_APP_URL: "http://localhost:8000"
      APP_URL: "http://localhost:8000"
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - redis
    command: >
      bash -c "composer install &&
               npm install &&
               npm run build &&
               php artisan migrate --force &&
               (npm run dev & php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000)"

  redis:
    image: redis:7-alpine
    container_name: fintech-assets-explorer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  node_modules:
